config/routes.rb
Rails.application.routes.draw do
  
  
  resources :timeslip_categories
  resources :labtech_dispatches do
    collection do 
      get  :autocomplete  
     end
  end
  
  resources :lab_ticket_statuses
  resources :backup_pcs
  resources :labtech_client_other_data
  resources :labtech_times do
      get :support_hours_report, :on => :collection
      get :client_timesheet_report, :on => :collection
      
  collection do
      get :import_timeslips
      get :update_timeslips
      get :client_hours_report
      
    end
  end
   
  resources :labtickets do
    resources :lab_dispatches
    get :open_tickets, :on => :collection
    get :qbr_tickets,  :on => :collection
    get :critical_drive,  :on => :collection
     get :printer_tickets,  :on => :collection
     get :extra_data,  :on => :collection
     get :c_tickets, :on => :collection
     get :new_tickets, :on => :collection
     get :monitors, :on => :collection
    collection do
      get 'ticket'
      get 'show_labticket'
      post 'make_labticket'
      get 'hd_critical'
      get 'download_tickets'
      end
    end
  resources :task_options
  resources :labtech_computers do
    collection do
      get :sync_computers
    end
  end
  
  resources :labtech_locations do
    collection do
      get :import_location
    end
  end
  
    
  resources :todo_lists
  resources :contract_service_lines
  resources :service_lists
  resources :service_types
  
  resources :computers
  resources :parts
  
  resources :locations
   
  
  resources :labtech_timeslips
  
 # get "create_ticket", to: "labtickets#create_ticket"
  
  
  resources :labtech_clients do
    resources :labtech_locations, :labtech_computers, :labtech_times
    get :get_client, :on => :collection
    collection do
      get :import_clients
      get :update_clients
      get 'lab_client'
    end
  end
   
  devise_for :users
  get 'sign_in' => 'devise/sessions#new'
  resources :labtech_audits do
    collection {post :import } 
  end
  get 'labtech_clients/import'
   resources :repairs do
    resources :malwares
  end
  put 'complete_malware', to: 'malwares#complete', as: :complete_malwares
  resources :malwares
 
  resources :repair_malware_cleans
  resources :repair_categories
  resources :events
  resources :projects do
    resources :comments
  end
  resources :assigned_teches
  resources :systems
  resources :comments do
    resources :comments
  end
  resources :types
  
  resources :tickets do
    resources :diagnostics
    resources :comments
  end
  resources :diagnostics
  
  resources :tickets do
    resources :ticket_comments
  end
  
  resources :backups do
    resources :comments
    resources :todo_lists
    collection do
      get 'merge'
      end
  end
  resources :contract_services do
    get :index2, :on => :collection
    collection do
      get 'merge'
    end
  end
  
  resources :anti_viri
  resources :issues
  resources :priorities
  resources :b_tasks do
    collection {post :import}
  end
 resources :clients do
    resources :tickets, :backups, :anti_viri, :contract_services, :comments
    collection do 
      get  :autocomplete 
      get 'merge'
      post :import 
    
     end
   end
  
   resources :dispatches do
    collection do 
      get  :autocomplete  
     end
   end
   
 get "/non_active", to: "contract_services#non_active", as: :non_active_contract_service
    
 
  resources :backups do
    resources :b_tasks
    resources :comments
  end
  resources :items
 
  resources :communications
  resources :tasks
  resources :it_services
  resources :service_categories
  resources :statuses
  resources :tests
  
  resources :pages
  
  get '/login', to: 'pages#login'
  
  # This is where we are redirected if OmniAuth successfully authenticates
  # the user.
  match '/auth/:provider/callback', to: 'pages#callback', via: [:get, :post]
  
  match '/send_mail', to: 'pages#send_mail', via: [:post]

  match '/disconnect', to: 'pages#disconnect', via: [:get]
  
  
  #get '/support_hours_report', to: 'labtech_times#support_hours_report', via: [:get], controller: 'labtech_times'
  root to: "welcome#index"
  get '/clients/search/:q', :to => 'clients#search', :as => :search
  resources :welcome do
    get :daily_hours_report, :on => :collection 
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/labtech_timeslip.rb
class LabtechTimeslip < ApplicationRecord
  require 'httparty'
  require 'labtech'
  
  before_save :token, :timeslip
  after_save :travel_time
  
  has_many :labtickets
  belongs_to :labtech_client
  belongs_to :user
  belongs_to :lab_ticket_status
  belongs_to :timeslip_category
  has_and_belongs_to_many :labtech_timeslips
  
  def token
   @token = HTTParty.post('http://labtech.core-pc.com/WCC2/API/APIToken', 
   :headers => { 'Content-Type' => 'application/json'},
   :body => "\n{\n  \"password\" : \"Chang3m3\",\n  \"username\" : \"robert\"\n}")
  
  
   end
  
   def timeslip
      @labuser = self.user_id
      @labclient =self.labtech_client_id
      @start = self.started_date
      @ticketid = self.lab_ticketid
      @hours = self.hours
      @mins = self.mins
      @category = self.labtime
      @subject = self.subject
      
     
      @response = HTTParty.post('http://labtech.core-pc.com/WCC2/API/TimeSlips/',
      :headers => {'Content-Type' => 'application/json', "Authorization" => "LTToken  #{@token}",
                 "User-Agent" => "robert" },
       :body => {
        "TimeSlipID": '0',
        "UserID": @labuser,
        "ClientID": @labclient,
        "ProjectID": '0',
        "TicketID": @ticketid,
        "Hours": @hours,
        "Mins": @mins,
        "Done": 'false',
        "Date": @start,
        "Description": @subject,
        "Billed": '0',
        "CategoryID": @category 
       }.to_json )
       puts @response.body
    end   
    
    def travel_time   
       if self.labtime == "5"
      @response1 = HTTParty.post('http://labtech.core-pc.com/WCC2/API/TimeSlips/',
       :headers => {'Content-Type' => 'application/json', "Authorization" => "LTToken  #{@token}",
                 "User-Agent" => "robert" },
       :body => {
        "TimeSlipID": '0',
        "UserID": @labuser,
        "ClientID": @labclient,
        "ProjectID": '0',
        "TicketID": @ticketid,
        "Hours": '0',
        "Mins": '15',
        "Done": 'false',
        "Date": @start - (15*60),
        "Description": 'Travel Time',
        "Billed": '0',
        "CategoryID": '9' 
       }.to_json )
       puts @response1.body
       else
         travel_times = ""
       end
      
   end
end

app/controllers/labtech_timeslips_controller.rb
class LabtechTimeslipsController < ApplicationController
  require 'labtech'
  before_action :set_labtech_timeslip, only: [:show, :edit, :update, :destroy]

  # GET /labtech_timeslips
  # GET /labtech_timeslips.json
  def index
    @labtech_timeslips = LabtechTimeslip.all
    @dtl_timeslips = LabtechTimeslip.all.where('lab_client_id = 12 ')
  end

  # GET /labtech_timeslips/1
  # GET /labtech_timeslips/1.json
  def show
    Labtech.get_token
    @last_ticket = Labtech.last_labticket
  end

  # GET /labtech_timeslips/new
  def new
    @labtech_timeslip = LabtechTimeslip.new
    @timeslip = LabtechTimeslip.all
  end

  # GET /labtech_timeslips/1/edit
  def edit
  end

  # POST /labtech_timeslips
  # POST /labtech_timeslips.json
  def create
    @labtech_timeslip = LabtechTimeslip.new(labtech_timeslip_params)

    respond_to do |format|
      if @labtech_timeslip.save
        format.html { redirect_to @labtech_timeslip, notice: 'Labtech timeslip was successfully created.' }
        format.json { render :show, status: :created, location: @labtech_timeslip }
      else
        format.html { render :new }
        format.json { render json: @labtech_timeslip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labtech_timeslips/1
  # PATCH/PUT /labtech_timeslips/1.json
  def update
    respond_to do |format|
      if @labtech_timeslip.update(labtech_timeslip_params)
        format.html { redirect_to @labtech_timeslip, notice: 'Labtech timeslip was successfully updated.' }
        format.json { render :show, status: :ok, location: @labtech_timeslip }
      else
        format.html { render :edit }
        format.json { render json: @labtech_timeslip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labtech_timeslips/1
  # DELETE /labtech_timeslips/1.json
  def destroy
    @labtech_timeslip.destroy
    respond_to do |format|
      format.html { redirect_to labtech_timeslips_url, notice: 'Labtech timeslip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_labtech_timeslip
      @labtech_timeslip = LabtechTimeslip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def labtech_timeslip_params
      params.require(:labtech_timeslip).permit(:name, :labtime, :started_date, :mins, :hours, :subject, :lab_client_id, :lab_ticketid, :labtech_client_id, :user_id )
    end
end

app/helpers/labtech_timeslips_helper.rb
module LabtechTimeslipsHelper
end

app/views/labtech_timeslips/Copy of show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @labtech_timeslip.name %>
</p>

<p>
  <strong>Labtime:</strong>
  <%= @labtech_timeslip.labtime %>
</p>
<div class="table-row header">
	
     <div class="col-xs col-md-1">TimeSlipID</div>
      <div class="col-xs col-md-1">UserID</div>
      <div class="col-xs col-md-1">ClientID</div>
      <div class="col-xs col-md-1">TicketID</div>
      <div class="col-xs col-md-1">Hours</div>
      <div class="col-xs col-md-1">Mins</div>
      <div class="col-xs col-md-1">Done</div>
      <div class="col-xs col-md-1">Date</div>
      <div class="col-xs col-md-2">Description</div>
     
      
   </div> 
  <% @timeslips['value'].each do |key| %>
     <div class="table-row">	
          <div class="col-xs col-md-1"><%= key['TimeSlipID'] %></div>
         <div class="col-xs col-md-1"><%= key['UserID'] %></div>
          <div class="col-xs col-md-1"><%= key['ClientID'] %></div>
           <div class="col-xs col-md-1"><%= key['TicketID'] %></div>
           <div class="col-xs col-md-1"><%= key['Hours'] %></div>
          <div class="col-xs col-md-1"><%= key['Mins'] %></div>
           <div class="col-xs col-md-1"><%= key['Done'] %></div>
           <div class="col-xs col-md-1"><%= key['Date'] %></div>
           <div class="col-xs col-md-2"><%= key['Description'] %></div>
           
       </div> 
        
    
    <% end %>  


<%= link_to 'Edit', edit_labtech_timeslip_path(@labtech_timeslip) %> |
<%= link_to 'Back', labtech_timeslips_path %>

app/views/labtech_timeslips/_form.html.erb
<div class="container">
<%= simple_form_for(@labtech_timeslip) do |f| %>
  <%= f.error_notification %>
   <h1>New Labtech Timeslip</h1>
    
	<div class="col-sm col-md  ">
  	
  	 <div class="col-sm-4 col-md-7">	
       
        <%= f.input :started_date %>
  		<%= f.association :user, selected: :current_user, label_method: :email, value_method: :labtech_id, prompt:
                     "Choose Tech", include_blank: false %>
  		<%= f.association :labtech_client, collection: LabtechClient.order(:name), label_method: :name, value_method: :lclient_id, prompt:
                     "Choose Client", include_blank: false %>
        
        
          <%= f.input :subject %>       
        
        
      </div>
      <div class="col-sm-4 col-md-4 ml-md-auto">
        <%= f.input :lab_ticketid %>         
        <%= f.input :labtime, collection: LabtechTimeslip.all, label_method: :name, value_method: :labtime, prompt: "Choose Categorie", include_blank: false %>
        <%= f.input :hours %>
        <%= f.input :mins %>
        </div>
      </div>
      <div class="align-center m-1">
  <div class="col-sm-3 col-md-3"> 
 <%= f.button :submit, class: "btn btn-primary form-control" %><br></br>
 </div>
 </div>
    <div class="row justify-content-md-center">
  <div class="col-xs px-5">
  <%= link_to 'Back', labtickets_path, class: "btn btn-primary", style: "width: 100px" %>
    </div>
  </div>

<% end %>
</div>

app/views/labtech_timeslips/edit.html.erb
<h1>Editing Labtech Timeslip</h1>

<%= render 'form', labtech_timeslip: @labtech_timeslip %>

<%= link_to 'Show', @labtech_timeslip %> |
<%= link_to 'Back', labtech_timeslips_path %>

app/views/labtech_timeslips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Labtech Timeslips</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Labtime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labtech_timeslips.each do |labtech_timeslip| %>
      <tr>
        <td><%= labtech_timeslip.name %></td>
        <td><%= labtech_timeslip.labtime %></td>
        <td><%= link_to 'Show', labtech_timeslip %></td>
        <td><%= link_to 'Edit', edit_labtech_timeslip_path(labtech_timeslip) %></td>
        <td><%= link_to 'Destroy', labtech_timeslip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Labtech Timeslip', new_labtech_timeslip_path %>

app/views/labtech_timeslips/new.html.erb
<%= render 'form', labtech_timeslip: @labtech_timeslip %>

app/views/labtech_timeslips/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid p-4">
<p>
  <strong>Name:</strong>
  <%= @labtech_timeslip.name %>
</p>

<p>
  <strong>Labtime:</strong>
  <%= @labtech_timeslip.labtime %>
</p>

	
<h3>Labtech Ticket</h3>


<div class="table-row header">
	
     <div class="col-xs col-md-1">TicketID</div>
      <div class="col-xs col-md-2">Client</div>
      <div class="col-xs col-md-1">ClientID</div>
      <div class="col-xs col-md-1">Computer</div>
      <div class="col-xs col-md-1">ID</div>
      <div class="col-xs col-md-2">Subject</div>
      <div class="col-xs col-md-1">Status</div>
      <div class="col-xs col-md-3">Date</div>
      
   </div> 

 
    <% @last_ticket['value'].each do |key| %>
     <div class="table-row">	
          <div class="col-xs col-md-1"><%= key['TicketID'] %></div>
         <div class="col-xs col-md-2"><%= key['Client'] %></div>
          <div class="col-xs col-md-1"><%= key['ClientID'] %></div>
           <div class="col-xs col-md-1"><%= key['Computer'] %></div>
           <div class="col-xs col-md-1"><%= key['ComputerID'] %></div>
          <div class="col-xs col-md-2"><%= key['Subject'] %></div>
           <div class="col-xs col-md-1"><%= key['Status'] %></div>
           <div class="col-xs col-md-3"><%= key['StartedDate'].to_datetime.strftime("%m-%d-%Y %I:%M:%S %p") %></div>
           
       </div> 
        
    
    <% end %>
	

</div>


<%= link_to 'Edit', edit_labtech_timeslip_path(@labtech_timeslip) %> |
<%= link_to 'Back', labtech_timeslips_path %>