config/routes.rb
Rails.application.routes.draw do
  
  
  resources :timeslip_categories
  resources :labtech_dispatches do
    collection do 
      get  :autocomplete  
     end
  end
  
  resources :lab_ticket_statuses
  resources :backup_pcs
  resources :labtech_client_other_data
  resources :labtech_times do
      get :support_hours_report, :on => :collection
      get :client_timesheet_report, :on => :collection
      
  collection do
      get :import_timeslips
      get :update_timeslips
      get :client_hours_report
      
    end
  end
   
  resources :labtickets do
    resources :lab_dispatches
    get :open_tickets, :on => :collection
    get :qbr_tickets,  :on => :collection
    get :critical_drive,  :on => :collection
     get :printer_tickets,  :on => :collection
     get :extra_data,  :on => :collection
     get :c_tickets, :on => :collection
     get :new_tickets, :on => :collection
     get :monitors, :on => :collection
    collection do
      get 'ticket'
      get 'show_labticket'
      post 'make_labticket'
      get 'hd_critical'
      get 'download_tickets'
      end
    end
  resources :task_options
  resources :labtech_computers do
    collection do
      get :sync_computers
    end
  end
  
  resources :labtech_locations do
    collection do
      get :import_location
    end
  end
  
    
  resources :todo_lists
  resources :contract_service_lines
  resources :service_lists
  resources :service_types
  
  resources :computers
  resources :parts
  
  resources :locations
   
  
  resources :labtech_timeslips
  
 # get "create_ticket", to: "labtickets#create_ticket"
  
  
  resources :labtech_clients do
    resources :labtech_locations, :labtech_computers, :labtech_times
    get :get_client, :on => :collection
    collection do
      get :import_clients
      get :update_clients
      get 'lab_client'
    end
  end
   
  devise_for :users
  get 'sign_in' => 'devise/sessions#new'
  resources :labtech_audits do
    collection {post :import } 
  end
  get 'labtech_clients/import'
   resources :repairs do
    resources :malwares
  end
  put 'complete_malware', to: 'malwares#complete', as: :complete_malwares
  resources :malwares
 
  resources :repair_malware_cleans
  resources :repair_categories
  resources :events
  resources :projects do
    resources :comments
  end
  resources :assigned_teches
  resources :systems
  resources :comments do
    resources :comments
  end
  resources :types
  
  resources :tickets do
    resources :diagnostics
    resources :comments
  end
  resources :diagnostics
  
  resources :tickets do
    resources :ticket_comments
  end
  
  resources :backups do
    resources :comments
    resources :todo_lists
    collection do
      get 'merge'
      end
  end
  resources :contract_services do
    get :index2, :on => :collection
    collection do
      get 'merge'
    end
  end
  
  resources :anti_viri
  resources :issues
  resources :priorities
  resources :b_tasks do
    collection {post :import}
  end
 resources :clients do
    resources :tickets, :backups, :anti_viri, :contract_services, :comments
    collection do 
      get  :autocomplete 
      get 'merge'
      post :import 
    
     end
   end
  
   resources :dispatches do
    collection do 
      get  :autocomplete  
     end
   end
   
 get "/non_active", to: "contract_services#non_active", as: :non_active_contract_service
    
 
  resources :backups do
    resources :b_tasks
    resources :comments
  end
  resources :items
 
  resources :communications
  resources :tasks
  resources :it_services
  resources :service_categories
  resources :statuses
  resources :tests
  
  resources :pages
  
  get '/login', to: 'pages#login'
  
  # This is where we are redirected if OmniAuth successfully authenticates
  # the user.
  match '/auth/:provider/callback', to: 'pages#callback', via: [:get, :post]
  
  match '/send_mail', to: 'pages#send_mail', via: [:post]

  match '/disconnect', to: 'pages#disconnect', via: [:get]
  
  
  #get '/support_hours_report', to: 'labtech_times#support_hours_report', via: [:get], controller: 'labtech_times'
  root to: "welcome#index"
  get '/clients/search/:q', :to => 'clients#search', :as => :search
  resources :welcome do
    get :daily_hours_report, :on => :collection 
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/ticket_comment.rb
class TicketComment < ApplicationRecord
 belongs_to :ticket
end

app/controllers/ticket_comments_controller.rb
class TicketCommentsController < ApplicationController
  before_action :set_comments, only: [:show, :edit, :update, :destroy] 
  before_action :set_comment, only: [:show, :edit, :update, :destroy] 

  # GET tickets/1/comments
  def index
    @comments = @ticket.comments
  
  end

  # GET tickets/1/comments/1
  def show
  end

  # GET tickets/1/comments/new
  def new
    @comment = @ticket.comments.build
  end

  # GET tickets/1/comments/1/edit
  def edit
  end

  # POST tickets/1/comments
  def create
      
  
    @comment = @ticket.comments.build(comment_params)
    

 
    if @comment.save
      redirect_to([@comment.ticket, @comment], notice: 'Comment was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT tickets/1/comments/1
  def update
    if @comment.update_attributes(comment_params)
      redirect_to([@comment.ticket, @comment], notice: 'Comment was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE tickets/1/comments/1
  def destroy
    @comment.destroy

    redirect_to ticket_comments_url(@ticket)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def set_comments
      @ticket = Ticket.find(params[:ticket_id])
    end

    def set_comment
      @comment = @ticket.comments.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:name, :content)
    end
end

app/helpers/ticket_comments_helper.rb
module TicketCommentsHelper
end

app/views/ticket_comments/_comment.html.erb
<li>
  
0
  <%= form_for [ticket_comment, Ticket_comment.new] do |f| %>
      <%= f.text_area :content, placeholder: "Add a Reply" %><br/>
      <%= f.submit "Reply"  %>
      <% end %>

  <ul>
      <%= render partial: 'ticket_comments/comment', collection: ticket_comment.ticket.comments %>
  </ul>

</li>

app/views/ticket_comments/_comments.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= ticket_comment.name %></td>
    <td><%= ticket_comment.content %></td>
    <td><%= link_to 'Show', [ticket_ticket_comment.ticket, ticket_comment] %></td>
    <td><%= link_to 'Edit', edit_ticket_ticket_comment_path(ticket_comment.ticket, ticket_comment) %></td>
    <td><%= link_to 'Destroy', [ticket_ticket_comment.ticket, ticket_comment], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_ticket_ticket_comment_path(params[:ticket_id]) %>

app/views/ticket_comments/_form.html.erb
<%= form_for([@ticket_comment.ticket, @ticket_comment]) do |f| %>
  <% if @ticket_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket_comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @ticket_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ticket_comments/_ticket_comment.html.erb
<p id="notice"><%= notice %></p>

	<div class="table-row-header">
	<h4>Enter Comments</h4>
<%= simple_form_for([@ticket_comment.ticket, @comment]) do |f| %>
  <% if @ticket_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket_comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @ticket_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="table-row">
  	<div><%= f.hidden_field :ticket_id, :value => params[:ticket_id] %></div>
    <div class="text-input input1"><%= f.text_field :name, placeholder: 'Name'%></div><br>
    <div class="text-input"><%= f.text_area :content, placeholder: 'Comments' %></div><br>
    				<div class="text-input"><%= f.button :submit, "Submit Task", class: "btn btn-primary" %></div>
    </div>
    </div>
   <% end %>
     

 

app/views/ticket_comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', [@ticket_comment.ticket, @ticket_comment] %> |
<%= link_to 'Back', ticket_ticket_comments_path(@ticket_comment.ticket) %>

app/views/ticket_comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ticket_comments.each do |comment| %>
  <tr>
    <td><%= ticket_comment.name %></td>
    <td><%= ticket_comment.content %></td>
    <td><%= link_to 'Show', [ticket_comment.ticket, ticket_comment] %></td>
    <td><%= link_to 'Edit', edit_ticket_ticket_comment_path(ticket_comment.ticket, ticket_comment) %></td>
    <td><%= link_to 'Destroy', [ticket_comment.ticket, ticket_comment], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_ticket_ticket_comment_path(params[:ticket_id]) %>

app/views/ticket_comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', ticket_ticket_comments_path(@ticket_comment.ticket) %>

app/views/ticket_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ticket_comment.name %>
</p>

<p>
  <b>Content:</b>
  <%= @ticket_comment.content %>
</p>


<%= link_to 'Edit', edit_ticket_comment_path(@ticket_comment.ticket, @ticket_comment) %> |
<%= link_to 'Back', ticket_comments_path(@ticket_comment.ticket) %>