config/routes.rb
Rails.application.routes.draw do
  
  
  resources :timeslip_categories
  resources :labtech_dispatches do
    collection do 
      get  :autocomplete  
     end
  end
  
  resources :lab_ticket_statuses
  resources :backup_pcs
  resources :labtech_client_other_data
  resources :labtech_times do
      get :support_hours_report, :on => :collection
      get :client_timesheet_report, :on => :collection
      
  collection do
      get :import_timeslips
      get :update_timeslips
      get :client_hours_report
      
    end
  end
   
  resources :labtickets do
    resources :lab_dispatches
    get :open_tickets, :on => :collection
    get :qbr_tickets,  :on => :collection
    get :critical_drive,  :on => :collection
     get :printer_tickets,  :on => :collection
     get :extra_data,  :on => :collection
     get :c_tickets, :on => :collection
     get :new_tickets, :on => :collection
     get :monitors, :on => :collection
    collection do
      get 'ticket'
      get 'show_labticket'
      post 'make_labticket'
      get 'hd_critical'
      get 'download_tickets'
      end
    end
  resources :task_options
  resources :labtech_computers do
    collection do
      get :sync_computers
    end
  end
  
  resources :labtech_locations do
    collection do
      get :import_location
    end
  end
  
    
  resources :todo_lists
  resources :contract_service_lines
  resources :service_lists
  resources :service_types
  
  resources :computers
  resources :parts
  
  resources :locations
   
  
  resources :labtech_timeslips
  
 # get "create_ticket", to: "labtickets#create_ticket"
  
  
  resources :labtech_clients do
    resources :labtech_locations, :labtech_computers, :labtech_times
    get :get_client, :on => :collection
    collection do
      get :import_clients
      get :update_clients
      get 'lab_client'
    end
  end
   
  devise_for :users
  get 'sign_in' => 'devise/sessions#new'
  resources :labtech_audits do
    collection {post :import } 
  end
  get 'labtech_clients/import'
   resources :repairs do
    resources :malwares
  end
  put 'complete_malware', to: 'malwares#complete', as: :complete_malwares
  resources :malwares
 
  resources :repair_malware_cleans
  resources :repair_categories
  resources :events
  resources :projects do
    resources :comments
  end
  resources :assigned_teches
  resources :systems
  resources :comments do
    resources :comments
  end
  resources :types
  
  resources :tickets do
    resources :diagnostics
    resources :comments
  end
  resources :diagnostics
  
  resources :tickets do
    resources :ticket_comments
  end
  
  resources :backups do
    resources :comments
    resources :todo_lists
    collection do
      get 'merge'
      end
  end
  resources :contract_services do
    get :index2, :on => :collection
    collection do
      get 'merge'
    end
  end
  
  resources :anti_viri
  resources :issues
  resources :priorities
  resources :b_tasks do
    collection {post :import}
  end
 resources :clients do
    resources :tickets, :backups, :anti_viri, :contract_services, :comments
    collection do 
      get  :autocomplete 
      get 'merge'
      post :import 
    
     end
   end
  
   resources :dispatches do
    collection do 
      get  :autocomplete  
     end
   end
   
 get "/non_active", to: "contract_services#non_active", as: :non_active_contract_service
    
 
  resources :backups do
    resources :b_tasks
    resources :comments
  end
  resources :items
 
  resources :communications
  resources :tasks
  resources :it_services
  resources :service_categories
  resources :statuses
  resources :tests
  
  resources :pages
  
  get '/login', to: 'pages#login'
  
  # This is where we are redirected if OmniAuth successfully authenticates
  # the user.
  match '/auth/:provider/callback', to: 'pages#callback', via: [:get, :post]
  
  match '/send_mail', to: 'pages#send_mail', via: [:post]

  match '/disconnect', to: 'pages#disconnect', via: [:get]
  
  
  #get '/support_hours_report', to: 'labtech_times#support_hours_report', via: [:get], controller: 'labtech_times'
  root to: "welcome#index"
  get '/clients/search/:q', :to => 'clients#search', :as => :search
  resources :welcome do
    get :daily_hours_report, :on => :collection 
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/labtech_client.rb
class LabtechClient < ApplicationRecord
  self.primary_key = "lclient_id"

has_many :labtickets, :dependent => :destroy
has_many :labtech_timeslips, :dependent => :destroy
has_many :labtech_locations, :dependent => :destroy
has_many :labtech_computers, :dependent => :destroy
has_many :labtech_client_other_datum
has_many :labtech_times, :foreign_key => "timeslip_id", :class_name => "LabtechTime"
has_many :backup_pcs
#before_validation :token, :set_lclient_id
#before_save :token
#before_save :add_client
#after_save :token, :update_labclient
#before_create :token, :set_lclient_id
accepts_nested_attributes_for :labtech_times

scope :contracts, -> { where('labtech_clients.support_mins > 0')}
scope :non_contract, -> { where('labtech_clients.support_mins = 0 ')}
scope :no_hours, -> {where(id: :lclient_id)}
#where("NOT EXISTS (SELECT null FROM labtech_clients where labtech_times.id = ?)", nil) }
    
 validates :id, uniqueness: true
 
    def self.search(search)
      
        where('first_name LIKE ? OR name LIKE ? OR lclient_id LIKE ? OR company_name LIKE ? 
        OR first_name LIKE ? OR phone LIKE ? ', 
        "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
       
    end
    paginates_per 10
    
end

app/controllers/labtech_clients_controller.rb
class LabtechClientsController < ApplicationController
  before_action :authenticate_user!
  
  before_action :set_labtech_client, only: [:show, :edit, :update, :destroy]
  #before_action :get_labclient, only: [:show]
  require 'labtech'
  require 'pp'
  require 'my_db'
  
  
  def token
   @token = HTTParty.post('http://labtech.core-pc.com/WCC2/API/APIToken', 
   :headers => { 'Content-Type' => 'application/json'},
   :body => "\n{\n  \"password\" : \"Chang3m3\",\n  \"username\" : \"robert\"\n}") 
   end

    def index
     @labtech_clients = LabtechClient.all.order(:name).page params[:page]
     if params[:search]
       @labtech_clients = LabtechClient.search(params[:search]).order("created_at DESC").page params[:page]
     else
       @labtech_clients = LabtechClient.all.order(:name).page params[:page]
     end
       
end
  # GET /labtech_labtech_clients/1
  # GET /labtech_labtech_clients/1.json
  def show
    if params[:search]
    render "partials/client", @labtech_clients.where(lclient_id => params[:search])
     else
       LabtechClient.all
     end
  end    
        #@response = response.parsed_response["value"]
        #@labtech_client = @response
   
  # GET /labtech_labtech_clients/new
  def import_clients
   
   
   @token = Labtech.get_token
   @labtech_client = Labtech.import_clients
   
    @labtech_client['value'].each do |key|
     
       LabtechClient.find_or_create_by(
           "lclient_id" => key['ClientID'],
           "name" => key['Name'],
           "company_name" => key['Company'],
           "first_name" => key['Firstname'],
           "last_name" => key['LastName'],
           "address1" => key['Address1'],
           "address2" => key['Address2'],
           "city" => key['City'],
           "state" => key['State'],
           "zip_code" => key['Zip'],
           "phone" => key['Phone'],
           "support_mins" => key['SupportMins']
           )
           
      end
     
      if @labtech_client.success?
         @labtech_client = LabtechClient.new 
        
         redirect_to labtech_clients_url, notice: 'Labtech Clients were successfully synced.'
      else
         redirect_to labtech_clients_url, notice: 'Labtech Clients failed to Sync.'
      end
    end 
    def update_clients
   
   
   @token = Labtech.get_token
   @labtech_client = Labtech.import_clients
   
    @labtech_client['value'].each do |key|
     
       LabtechClient.first_or_initialize.update_attributes!(
           "lclient_id" => key['ClientID'],
           "name" => key['Name'],
           "company_name" => key['Company'],
           "first_name" => key['Firstname'],
           "last_name" => key['LastName'],
           "address1" => key['Address1'],
           "address2" => key['Address2'],
           "city" => key['City'],
           "state" => key['State'],
           "zip_code" => key['Zip'],
           "phone" => key['Phone'],
           "support_mins" => key['SupportMins']
           )
           
      end
     
      if @labtech_client.success?
         @labtech_client = LabtechClient.new 
        
         redirect_to labtech_clients_url, notice: 'Labtech Clients were successfully synced.'
      else
         redirect_to labtech_clients_url, notice: 'Labtech Clients failed to Sync.'
      end
    end 
  def lab_client
   
        
        @labtech_client = LabtechClient.where(:lclient_id => params[:company])
        if @labtech_client.success?
          
        end 
          
   end
   def lab_client1
     if params[:company_name].nil?
        @token = Labtech.get_token
        @labclient = LabtechClient.where(params[:id]) 
        
      else
        @token = Labtech.get_token
        @labclient = Labtech.show_clients
          
     end
   end  
  def new
     
   @labtech_client = LabtechClient.new
       
  end

  # GET /labtech_labtech_clients/1/edit
  def edit
  end

  # POST /labtech_labtech_clients
  # POST /labtech_labtech_clients.json
   def create
     
    @labtech_client = LabtechClient.new(labtech_client_params)
    
    
     respond_to do |format|
      if @labtech_client.save
      
     
   
        format.html { redirect_to @labtech_client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @labtech_client }
      else
        format.html { render :new }
        format.json { render json: @labtech_client.errors, status: :unprocessable_entity }
      end
   end
  end

  def edit
    
    #@labtech_clients = JSON.parse(labtech_clients, :symbolize_names => true)
  end

  def update
    
   respond_to do |format|
      if @labtech_client.save
        format.html { redirect_to @labtech_client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :created, location: @labtech_client }
      else
        format.html { render :new }
        format.json { render json: @labtech_client.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
     @labtech_client.destroy
    respond_to do |format|
      format.html { redirect_to labtech_clients_url, notice: 'Labtech_Client was successfully destroyed.' }
      format.json { head :no_content }
  end
 end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_labtech_client
      @labtech_client = LabtechClient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def labtech_client_params
      params.require(:labtech_client).permit(:name, :lclient_id, :company_name, :first_name, :last_name, :address1, :address2,
                     :city, :state, :phone, :zip_code, :support_mins,
                     labtech_locations_attributes: [:name, :labcomputer_id, :labtech_client_id, :labtech_location_id, :lablocation_id, 
                     :address, :city, :state, :zip, :phone, :fax, :comments])
    end
end

app/helpers/labtech_clients_helper.rb
module LabtechClientsHelper
end

app/views/labtech_clients/_client.html.erb
<p id="notice"><%= notice %></p>

 	
   
    <div class="container-fluid m-5">
    <h1>Labtech Client Info</h1>
   
 	<div class="table-row header">
 	
	<div class="text2 width5">ClientID</div>
	<div class="text1 width5">Name</div>
	
		    </div>  
	     <div class="table-row">	
	       <div class="text2 width5"><%= @labtech_client.id%></div>
	       <div class="text1 width5"><%= @labtech_client.name%></div>
	      
	        </div>
	        </br><div class="flex-center">
	        	
 		<%= link_to 'Back', labtech_clients_path, class: "btn btn-primary" %>
 	</div>
	
	</div>
 	

app/views/labtech_clients/_form.html.erb
<%= simple_form_for(@labtech_client) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
  	<div class="col-sm-4">
    <%= f.input :company_name %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :phone %>
    
    <%= f.input :address1 %>
    <%= f.input :address2 %>
    <%= f.input :city %> <%= f.input :state %>  <%= f.input :zip_code %>
    <%= f.button :submit, class: "btn btn-primary form-control" %> </br></br>
  </div>
    
    <div class="flex-center col-sm-12">
  <%= link_to 'Back', labtech_clients_path %>
  </div>
    
  </div>
  
<% end %>

app/views/labtech_clients/_get_client.html.erb
<%= form_tag({controller => "labtech_client", :action => "lab_client" }, method: "get") %>
	<div class="row align-items-start align-center">		
      <form class="form-inline">

      
    
       <%= text_field_tag(:company, "", placeholder: 'Enter Company', class: 'ml-1 p-2 m-1', style: 'height: 31px')%>
     
       <%= submit_tag "Show Client", class: "btn btn-primary form-control ml-3", style: "width: 150px" %> 
      </form>
      
   </div>
   
    <div class="container-fluid m-5">
    <h1>Labtech Client Info</h1>

 	<div class="table-row header">
 	
	<div class="text2 width5">ClientID</div>
	<div class="text1 width5">Name</div>
	
		    </div>  
		 
		  
	      <div class="table-row">	
	       <div class="text2 width5"><%= @labtech_client.id%></div>
	       <div class="text1 width5"><%= @labtech_client.name%></div>
	      
	        </div>
	 
	</div>
 

app/views/labtech_clients/_lab_index.html.erb
<p id="notice"><%= notice %></p>
 <div class="container-margin">
<h1>Labtech Clients</h1>

<%= @clientid %>

 	<div class="table-row header">
  	
 	
	<div class="text2 width5">ClientID</div>
	<div class="text1 width5">Name</div>
	<div class="text2 width5">First Name</div>
	<div class="text2 width5">Last Name</div>
	<div class="text2 width4">Company</div>
	<div class="text2 width5">Phone</div>
	<div class="text1 width5">Address</div>
		    </div>  
		     
		     <% @response['value'].each do |key| %>
	      <div class="table-row">	
	       <div class="text2 width5"><%= key['ClientID']%></div>
	       <div class="text1 width5"><%= key['Name']%></div>
	       <div class="text2 width5"><%= key['Firstname']%></div>
	       <div class="text2 width5"><%= key['LastName']%></div>
	       <div class="text2 width4"><%= key['Company']%></div>
	       <div class="text2 width5"><%= key['Phone']%></div>
	       <div class="text1 width5"><%= key['Address1']%></div>
	        </div>
	      
	     
   			 <% end %>
 
<%= link_to 'New Labtech Client', new_labtech_client_path %>
</div>

app/views/labtech_clients/edit.html.erb
<h1>Editing Labtech Client</h1>

<%= render 'form', labtech_client: @labtech_client %>

<%= link_to 'Show', @labtech_client %> |
<%= link_to 'Back', labtech_clients_path %>

app/views/labtech_clients/get_client.html.erb
  <%= form_tag({controller => "labtech_client", :action => "get_client" }, method: "get") %>
	<div class="row align-items-start align-center">		
      <form class="form-inline">

      
    
       <%= text_field_tag(:company_name, "", placeholder: 'Enter Company', class: 'ml-1 p-2 m-1', style: 'height: 31px')%>
     
       <%= submit_tag "Show Client", class: "btn btn-primary form-control ml-3", style: "width: 150px" %> 
      </form>
      
   </div>
   
  
  <div class="container-fluid m-5">
    <h1>Labtech Client Info</h1>

 	<div class="table-row header">
 	
	<div class="col-xs-1 col-md-1">ClientID</div>
	<div class="col-xs-1 col-md-1">Name</div>
	
	
		    </div>  
		 
		    
	      <div class="table-row">	
	       <div class="col-xs-1 col-md-1"><%= labtech_client.id%></div>
	       <div class="col-xs-1 col-md-1"><%= labtech_client.name%></div>
	       
	       
	         
	        </div>
	 
	
   <% end %>
   <h4>Labtech Location Info</h4> 
   <div class="table-row header">
 	
	<div class="text2 width5">ID</div>
	<div class="text1 width5">Name</div>
	
	
		    </div>
		      
		 
	      <div class="table-row">
	      	<div class="text1 width5"><%= labtech_client.lclient.id %></div>
	        <div class="text1 width5"><%= labtech_cleint.name %></div>
	  
	      
	       
	        </div>
	 
	</div>
   <% end %>
   </div>             

app/views/labtech_clients/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid m-2 p-2"> 
	<div class="col-12">
<h4>Labtech Clients</h4>

<p id="notice"><%= notice %></p>	
	<div class="align-center">
	  
      <%= form_tag(labtech_clients_path, method: "get" , id: "search-form") do %>
      <%= label_tag(:search, "Search for:") %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Labtech Clients" %>
      <%= submit_tag "Search", :name => nil %>
      <% end %> </div>
      
         <div class="align-center">
        	<%= paginate @labtech_clients %> 	
        </div>
      		 
	
 	<div class="table-row header">
  	
 	
	<div class="text1 width2 hidden-xs-down">ID</div>
	<div class="text1 width2">Name</div>
	<div class="text1 width5">Address</div>
	<div class="text1 width5 hidden-xs-down">Phone</div>
	
	</div>
	
	 <% @labtech_clients.each do |labtech_client| %>
	       <div class="table-row">	
	       <div class="text1 width2 hidden-xs-down"><%= link_to labtech_client.id, labtech_client%></div>
	       <div class="text1 width2"><%= link_to labtech_client.name, labtech_client%></div>
	       <div class="text1 width5"><%= link_to labtech_client.address1, 'http://google.com/maps/search/'+labtech_client.address1+','+labtech_client.city, :target => "_blank"%></div>	       
	       <div class="text1 width5 hidden-xs-down"><%= labtech_client.phone%></div>
	       </div>
	      
	       
	   <% end %>
	  <div class="align-center"> <%= paginate @labtech_clients %> </div> 
	      
	    
 
  <div class="align-center m-1"> <%= link_to 'New Labtech Client', new_labtech_client_path, class: "btn btn-primary" %></div>
   <% if current_user.admin? %>
     <div class="align-center"> <%= link_to 'Sync Labtech Clients', import_clients_labtech_clients_path, class: "btn btn-primary" %> </div>
     <div class="align-center m-1"> <%= link_to 'Update Labtech Clients', update_clients_labtech_clients_path, class: "btn btn-primary" %> </div>
     
     <div class="align-center m-1"> <%= link_to "Get LabClient", get_client_labtech_clients_path, object: @lab_client, class: 'btn btn-primary' %></div>
    <% end %>
  </div>
</div>

app/views/labtech_clients/new.html.erb
<h1>New Labtech Client</h1>

<%= render 'form', labtech_client: @labtech_client %>

<%= link_to 'Back', labtech_clients_path %>

app/views/labtech_clients/show.html.erb
<p id="notice"><%= notice %></p>

 	<div class="container">
 		 <div class="row flex-space-around font-size table-row header">
 		
 	 <div class="col-xs font-size">Client</div>
 	 
	 <div class="col-xs font-size hidden-xs-down">Computers</div>
 	 <div class="col-xs font-size hidden-xs-down">Users</div>
 	 </div>
     <div class="table-row">
 	 <div class="col-xs font-size"><%= @labtech_client.name %></br>
 	  <%= @labtech_client.phone%></br> 	 
 	  <%= link_to @labtech_client.address1, 'http://google.com/maps/search/'+@labtech_client.address1+','+@labtech_client.city, :target => "_blank"%>
 	   </br>
 	   <%= @labtech_client.city %>, <%= @labtech_client.state %> </div>
 	   
 	   <div class="col-xs hidden-xs-down">blank </div>
 	   <div class="col-xs hidden-xs-down">blank </div>
 	   </div>
 	   
 	
 	<div class="row align-items-start align-center">
 	 <form class="form-inline">	
 	     <%= form_tag labtech_clients_path, method: "get" %>
	     <%= text_field_tag :search, params[:search], placeholder: 'Enter Company ID', class: 'ml-1 p-2 m-1', style: 'height: 31px'%>
         <%= submit_tag "Show Client", :name => nil, class: "btn btn-primary form-control ml-3", style: "width: 150px" %> 
     </form>
  
    </div>
   
   