config/routes.rb
Rails.application.routes.draw do
  
  
  resources :timeslip_categories
  resources :labtech_dispatches do
    collection do 
      get  :autocomplete  
     end
  end
  
  resources :lab_ticket_statuses
  resources :backup_pcs
  resources :labtech_client_other_data
  resources :labtech_times do
      get :support_hours_report, :on => :collection
      get :client_timesheet_report, :on => :collection
      
  collection do
      get :import_timeslips
      get :update_timeslips
      get :client_hours_report
      
    end
  end
   
  resources :labtickets do
    resources :lab_dispatches
    get :open_tickets, :on => :collection
    get :qbr_tickets,  :on => :collection
    get :critical_drive,  :on => :collection
     get :printer_tickets,  :on => :collection
     get :extra_data,  :on => :collection
     get :c_tickets, :on => :collection
     get :new_tickets, :on => :collection
     get :monitors, :on => :collection
    collection do
      get 'ticket'
      get 'show_labticket'
      post 'make_labticket'
      get 'hd_critical'
      get 'download_tickets'
      end
    end
  resources :task_options
  resources :labtech_computers do
    collection do
      get :sync_computers
    end
  end
  
  resources :labtech_locations do
    collection do
      get :import_location
    end
  end
  
    
  resources :todo_lists
  resources :contract_service_lines
  resources :service_lists
  resources :service_types
  
  resources :computers
  resources :parts
  
  resources :locations
   
  
  resources :labtech_timeslips
  
 # get "create_ticket", to: "labtickets#create_ticket"
  
  
  resources :labtech_clients do
    resources :labtech_locations, :labtech_computers, :labtech_times
    get :get_client, :on => :collection
    collection do
      get :import_clients
      get :update_clients
      get 'lab_client'
    end
  end
   
  devise_for :users
  get 'sign_in' => 'devise/sessions#new'
  resources :labtech_audits do
    collection {post :import } 
  end
  get 'labtech_clients/import'
   resources :repairs do
    resources :malwares
  end
  put 'complete_malware', to: 'malwares#complete', as: :complete_malwares
  resources :malwares
 
  resources :repair_malware_cleans
  resources :repair_categories
  resources :events
  resources :projects do
    resources :comments
  end
  resources :assigned_teches
  resources :systems
  resources :comments do
    resources :comments
  end
  resources :types
  
  resources :tickets do
    resources :diagnostics
    resources :comments
  end
  resources :diagnostics
  
  resources :tickets do
    resources :ticket_comments
  end
  
  resources :backups do
    resources :comments
    resources :todo_lists
    collection do
      get 'merge'
      end
  end
  resources :contract_services do
    get :index2, :on => :collection
    collection do
      get 'merge'
    end
  end
  
  resources :anti_viri
  resources :issues
  resources :priorities
  resources :b_tasks do
    collection {post :import}
  end
 resources :clients do
    resources :tickets, :backups, :anti_viri, :contract_services, :comments
    collection do 
      get  :autocomplete 
      get 'merge'
      post :import 
    
     end
   end
  
   resources :dispatches do
    collection do 
      get  :autocomplete  
     end
   end
   
 get "/non_active", to: "contract_services#non_active", as: :non_active_contract_service
    
 
  resources :backups do
    resources :b_tasks
    resources :comments
  end
  resources :items
 
  resources :communications
  resources :tasks
  resources :it_services
  resources :service_categories
  resources :statuses
  resources :tests
  
  resources :pages
  
  get '/login', to: 'pages#login'
  
  # This is where we are redirected if OmniAuth successfully authenticates
  # the user.
  match '/auth/:provider/callback', to: 'pages#callback', via: [:get, :post]
  
  match '/send_mail', to: 'pages#send_mail', via: [:post]

  match '/disconnect', to: 'pages#disconnect', via: [:get]
  
  
  #get '/support_hours_report', to: 'labtech_times#support_hours_report', via: [:get], controller: 'labtech_times'
  root to: "welcome#index"
  get '/clients/search/:q', :to => 'clients#search', :as => :search
  resources :welcome do
    get :daily_hours_report, :on => :collection 
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/labtech_computer.rb
class LabtechComputer < ApplicationRecord
   # self.primary_key = "computerid"
  belongs_to :labtech_client
  belongs_to :labtech_location
  belongs_to :backup
  has_many :labtickets
  has_many :backup_pcs, dependent: :destroy
  has_many :labtech_times, :foreign_key => "timeslip_id", :class_name => "LabtechTime"
  has_many :computers
end

app/controllers/labtech_computers_controller.rb
class LabtechComputersController < ApplicationController
  
  before_action :set_labtech_computer, only: [:show, :edit, :update, :destroy]
  require 'my_db'
  
 
  def index
    @labtech_computers = LabtechComputer.all
    @labtech_locations = LabtechComputer.joins(:labtech_location)
    
  end

  # GET /labtech_computers/1
  # GET /labtech_computers/1.json
  def show
  end
  def show_servers
    @labtech_computers = LabtechComputer.where('os like Windows Server').order(:company)
  end
 
   def sync_computers
     db = MyDb.conn
     sql = "SELECT clients.*, computers.*
           FROM computers
           JOIN clients ON computers.clientid=clients.clientid
           WHERE clients.clientid = computers.clientid
           ORDER BY clients.Name "
          
    @results = db.query(sql)  
    db.close
    
     @results.each do |row|
       LabtechComputer.find_or_create_by(
       "labcomputer_id" => row['ComputerID'],
       "lclient_id" => row['ClientID'],
       "lablocation_id" => row['LocationID'],
       "name" => row['Name'],
       "domain" => row['Domain'],
       "username" => row['LastUsername'],
       "lastcontact" => row['LastContact'],
       "os" => row['OS'] )
  
   end
      if @labtech_computer.save?
        redirect_to labtech_computers_url, notice: 'Labtech Computers was successfully synced.'
     else
        redirect_to labtech_computers_url, notice: 'Labtech Computer Sync was not successfull.'        
     end
  end

  # GET /labtech_computers/new
  def new
    @labtech_computer = LabtechComputer.new
    
  end

  # GET /labtech_computers/1/edit
  def edit
  end

  # POST /labtech_computers
  # POST /labtech_computers.json
  def create
    @labtech_computer = LabtechComputer.new(labtech_computer_params)

    respond_to do |format|
      if @labtech_computer.save
        format.html { redirect_to @labtech_computer, notice: 'Labtech computer was successfully created.' }
        format.json { render :show, status: :created, location: @labtech_computer }
      else
        format.html { render :new }
        format.json { render json: @labtech_computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labtech_computers/1
  # PATCH/PUT /labtech_computers/1.json
  def update
    respond_to do |format|
      if @labtech_computer.update(labtech_computer_params)
        format.html { redirect_to @labtech_computer, notice: 'Labtech computer was successfully updated.' }
        format.json { render :show, status: :ok, location: @labtech_computer }
      else
        format.html { render :edit }
        format.json { render json: @labtech_computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labtech_computers/1
  # DELETE /labtech_computers/1.json
  def destroy
    @labtech_computer.destroy
    respond_to do |format|
      format.html { redirect_to labtech_computers_url, notice: 'Labtech computer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_labtech_computer
      @labtech_computer = LabtechComputer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def labtech_computer_params
      params.require(:labtech_computer).permit(:computer, :labcomputer_id, :lablocation_id, :lclient_id, :labtech_location_id,
                      :name, :username, :os, :domain, :company, :clientid, :locationid, :computerid, :lastcontact, 
     labtech_locations_attributes: [:labtech_location_id, :name, :labcomputer_id, :labtech_client_id, :lclient_id, :lablocation_id, 
                     :address, :city, :state, :zip, :phone, :fax, :comments])
    end
end

app/helpers/labtech_computers_helper.rb
module LabtechComputersHelper
end

app/views/labtech_computers/_form.html.erb
<%= simple_form_for(@labtech_computer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :computer %>
    <%= f.input :labtech_client %>
    <%= f.input :labtech_location %>
    <%= f.input :name %>
    <%= f.input :username %>
    <%= f.input :os %>
    <%= f.input :domain %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/labtech_computers/edit.html.erb
<h1>Editing Labtech Computer</h1>

<%= render 'form', labtech_computer: @labtech_computer %>

<%= link_to 'Show', @labtech_computer %> |
<%= link_to 'Back', labtech_computers_path %>

app/views/labtech_computers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid m-3 p-3">

<h1>Labtech Computers</h1>

<table>
  <thead>
    <tr>
      <th>Computer</th>
      <th>Labtech client</th>
      <th>Labtech location</th>
      <th>Name</th>
      <th>Username</th>
      <th>Os</th>
      <th>Domain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labtech_computers.each do |labtech_computer| %>
      <tr>
        <td><%= link_to labtech_computer.id, labtech_computer %></td>
        <td><%= link_to labtech_computer.lclient_id, labtech_client_path(labtech_computer.lclient_id) %></td>
        <td><%= link_to labtech_computer.lablocation_id, labtech_location_path(labtech_computer.lablocation_id) %></td>
        <td><%= labtech_computer.name %></td>
        <td><%= labtech_computer.username %></td>
        <td><%= labtech_computer.os %></td>
        <td><%= labtech_computer.domain %></td>
        <td><%= link_to 'Show', labtech_computer %></td>
        <td><%= link_to 'Edit', edit_labtech_computer_path(labtech_computer) %></td>
        <td><%= link_to 'Destroy', labtech_computer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Labtech Computer', new_labtech_computer_path %>
<%= link_to 'Sync Computers', sync_computers_labtech_computers_path %>
</div>

app/views/labtech_computers/new.html.erb
<h1>New Labtech Computer</h1>

<%= render 'form', labtech_computer: @labtech_computer %>

<%= link_to 'Back', labtech_computers_path %>

app/views/labtech_computers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Computer:</strong>
  <%= @labtech_computer.id %>
</p>

<p>
  <strong>Labtech client:</strong>
  <%= @labtech_computer.labtech_client %>
</p>

<p>
  <strong>Labtech location:</strong>
  <%= @labtech_computer.labtech_location %>
</p>

<p>
  <strong>Name:</strong>
  <%= @labtech_computer.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @labtech_computer.username %>
</p>

<p>
  <strong>Os:</strong>
  <%= @labtech_computer.os %>
</p>

<p>
  <strong>Domain:</strong>
  <%= @labtech_computer.domain %>
</p>

<%= link_to 'Edit', edit_labtech_computer_path(@labtech_computer) %> |
<%= link_to 'Back', labtech_computers_path %>